set SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=0
set SETUPTOOLS_DISABLE_VERSIONED_EASY_INSTALL_SCRIPT=0
set DISTRIBUTE_DISABLE_VERSIONED_EASY_INSTALL_SCRIPT=0

%PYTHON% setup.py install
if errorlevel 1 exit 1
