#!/bin/bash

export SETUPTOOLS_DISABLE_VERSIONED_EASY_INSTALL_SCRIPT=0
export DISTRIBUTE_DISABLE_VERSIONED_EASY_INSTALL_SCRIPT=0

export SETUPTOOLS_DISABLE_EXTRAS_REQUIRE=1
export DISTRIBUTE_DISABLE_EXTRAS_REQUIRE=1

$PYTHON setup.py install
