{% set version = "34.1.1" %}

package:
  name: setuptools
  version: {{ version }}

source:
  fn: setuptools-{{ version }}.tar.gz
  url: https://github.com/pypa/setuptools/archive/v{{ version }}.tar.gz
  sha256: be2108849161624b51b2a5cdba8117e2b3f7a9cf4301cf3839a55afc3a7253e4
  patches:
    # Modify setuptools to fail if used in conda build (encourage people to add all deps in meta.yaml).
    - nodownload.patch

build:
  number: 0
  entry_points:
    - easy_install = setuptools.command.easy_install:main

requirements:
  build:
    - python
    - appdirs
    - certifi
    - packaging
    - six
    - wincertstore  # [win]
  run:
    - python
    - appdirs
    - certifi
    - packaging
    - six
    - wincertstore  # [win]

test:
  commands:
    - easy_install --help
  imports:
    - setuptools
    - easy_install
    - pkg_resources

about:
  home: https://github.com/pypa/setuptools
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  doc_url: http://pythonhosted.org/setuptools/
  dev_url: https://github.com/pypa/setuptools

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - nicoddemus
    - ocefpaf
