{% set version = "60.10.0" %}

package:
  name: setuptools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools/setuptools-{{ version }}.tar.gz
  sha256: 6599055eeb23bfef457d5605d33a4d68804266e6cb430b0fb12417c5efeae36c
  patches:
    # distutils patches from python-feedstock
    - patches/0012-Disable-new-dtags-in-unixccompiler.py.patch  # [py<=39]
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
    - patches/0010-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch  # [py<=39 and python_impl=="cpython"]

build:
  skip: true  # [py<36]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python

test:
  imports:
    - setuptools
    - pkg_resources

about:
  home: https://github.com/pypa/setuptools
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  doc_url: http://pythonhosted.org/setuptools/
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/master/docs

extra:
  recipe-maintainers:
    - rgommers
    - jakirkham
    - msarahan
    - ocefpaf
    - nicoddemus
    - isuruf
