{% set version = "67.5.0" %}

package:
  name: setuptools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools/setuptools-{{ version }}.tar.gz
  sha256: 113ff8d482b826d2f3b99f26adb1fe505e526a94a08e68cdf392d1dff9ce0595
  patches:
    # distutils patches from python-feedstock
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - setuptools
    - pkg_resources

about:
  home: https://github.com/pypa/setuptools
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  doc_url: http://pythonhosted.org/setuptools/
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/master/docs

extra:
  recipe-maintainers:
    - rgommers
    - jakirkham
    - msarahan
    - ocefpaf
    - nicoddemus
    - isuruf
