context:
  version: 80.10.1

package:
  name: setuptools
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/setuptools/setuptools-${{ version }}.tar.gz
  sha256: bf2e513eb8144c3298a3bd28ab1a5edb739131ec5c22e045ff93cd7f5319703a
  patches:
    # distutils patches from python-feedstock
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch

build:
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - setuptools
        - pkg_resources
      pip_check: true
      # The linter will complain about the missing python_min, but we need
      # this unpinned to allow setuptools to be used in the downstream tests
      # of the python-feedstock.
      # See also https://github.com/conda-forge/conda-forge.github.io/pull/2387
      python_version: python    

about:
  homepage: https://github.com/pypa/setuptools
  license: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  documentation: http://pythonhosted.org/setuptools/
  repository: https://github.com/pypa/setuptools

extra:
  recipe-maintainers:
    - xhochy
    - rgommers
    - jakirkham
    - msarahan
    - ocefpaf
    - nicoddemus
    - isuruf
